steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'frontend-build', '--target', 'build', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['run', 'frontend-build', 'ls', '-l', '/app/dist']
